routes.py
# flask
from flask import Blueprint, render_template, abort, flash, redirect, url_for, request, current_app
# login 
from flask_login import login_required, login_user, logout_user
# db models
from models import Song, User
# app extensions
from app import ts, db, send_mail, audio
# secure filename
from werkzeug.utils import secure_filename
import os
# blueprint
player_bp = Blueprint("player_bp", __name__, url_prefix="/")


@player_bp.route('/', methods=['GET'])
def home():
    try:
        # get published songs
        songs = Song.query.filter_by(published=True).all()
        # render player
        return render_template('player.html', songs=songs)
    except:
        abort(500)

@player_bp.route('/about', methods=['GET'])
def about():
    try:
        return render_template('about.html')
    except:
        abort(500)

# AUTHENTICATION
@player_bp.route('/confirm/<token>', methods=['GET', 'POST'])
def confirm_email(token):
    # check validity of token passed using the serializer
    try:
        email = ts.loads(token, salt="email-confirm-key", max_age=86400)
    except:
        abort(400)

    try:
        # get the user using the email
        user = User.query.filter_by(email=email).first_or_404()
        # confirm user
        user.confirmed = True
        # save changes in database
        db.session.commit()
        db.session.close()
        # alert user
        flash("email confirmed")
        # redirect to sign in
        return redirect(url_for('signin'))
    except:
        abort(500)


@player_bp.route('/signin', methods=['GET', 'POST'])
def signin():
    try:
        if request.method == 'POST':
            # get data from form
            email = request.form['email']
            password = request.form['password']
            # query by email
            user = User.query.filter_by(email=email).first()
            # check credentials
            if not user or not user.check_password(password):
                # alert user
                flash('invalid credentials')
                # redirect to sign in 
                return redirect(url_for('player_bp.signin'))
            # login user using the manager
            login_user(user)
            # redirect to upload page
            flash('signed in')
            # redirect to cms page
            return redirect(url_for('player_bp.cms'))
        # redner sign in page
        return render_template('signin.html')
    except:
        abort(500)


@player_bp.route('/reset', methods=['GET', 'POST'])
def reset():
    try:
        if request.method == 'POST':
            # get email from form
            email = request.form['email']
            # query user by emeail
            user = User.query.filter_by(email=email).first()
            # prepare email
            subject = "reset requested."
            # generate token
            token = ts.dumps(user.email, salt='recover-key')
            # build recover url
            recover_url = url_for(
                'player_bp.change',
                token=token,
                _external=True)
            # send the email
            send_mail(subject, current_app.config['MAIL_USERNAME'],
                      [email], recover_url)
            # alert user
            flash("reset link sent")
            # redirect to player
            return redirect(url_for('player_bp.home'))
        # render reset page
        return render_template('reset.html')
    except:
        abort(500)


@player_bp.route('/reset/<token>', methods=['GET', 'POST'])
def change(token):
    # check validity of token passed using the serializer
    try:
        email = ts.loads(token, salt="recover-key", max_age=86400)
    except:
        abort(400)
    # change password if valid token provided
    if request.method == 'POST':
        # get new password from form
        password = request.form['password']
        # get user using email
        user = User.query.filter_by(email=email).first_or_404()
        # set hashed password in database
        user.update_password(password)
        # save changes in database
        db.session.commit()
        db.session.close()
        # alert user
        flash("password changed")
        # redirect to sign in page
        return redirect(url_for('player_bp.signin'))
    # render password change page
    return render_template('change.html', token=token)

@player_bp.route('/signout')
def signout():
    try:
        # alert user
        flash('signed out')
        # sign out currently logged unser & redirect
        logout_user()
        # redirect to player
        return redirect(url_for('player_bp.home'))
    except:
        abort(500)


# CMS
@player_bp.route('/cms', methods=['GET'])
@login_required
def cms():
    try:
        # get all songs in the database
        songs = Song.query.order_by(Song.id.desc()).all()
        #print([song.mp3_filename for song in songs])
        return render_template('cms.html', songs=songs)
    except:
        abort(500)

@player_bp.route('/delete/<int:id>', methods=['POST'])
@login_required
def delete(id):
    try:
        song = Song.query.filter_by(id=id).first()
        # try:
        # remove mp3 and webm files from disk if present
        webm_path = current_app.config['BASE_DIR'] + url_for('static',
                                                   filename='audio/' + song.webm_filename)
        mp3_path = current_app.config['BASE_DIR'] + url_for('static',
                                                   filename='audio/' + song.mp3_filename)
        # remove if they exist
        if os.path.exists(webm_path):
            # delete
            os.remove(webm_path)
        if os.path.exists(mp3_path):
            # delete
            os.remove(mp3_path)
        # delete from db
        db.session.delete(song)
        db.session.commit()
        db.session.close()
        # alert user
        flash('song deleted')
        # redirect to cms
        return redirect(url_for('player_bp.cms'))
    except:
        abort(500)


@player_bp.route('/publish/<int:id>', methods=['POST'])
@login_required
def publish(id):
    try:
        # get song by  id
        song = Song.query.filter_by(id=id).first()
        # set published to true
        song.published = True
        # commit to database
        db.session.commit()
        db.session.close()
        # alert user
        flash('published')
        # redirect to cms
        return redirect(url_for('player_bp.cms'))
    except:
        abort(500)


@player_bp.route('/unpublish/<int:id>', methods=['POST'])
@login_required
def unpublish(id):
    try:
        # get song
        song = Song.query.filter_by(id=id).first()
        # set published to true
        song.published = False
        # commit to database
        db.session.commit()
        db.session.close()
        # alert user
        flash('unpublished')
        # redirect to cms
        return redirect(url_for('player_bp.cms'))
    except:
        abort(500)

@player_bp.route('/upload', methods=['GET', 'POST'])
@login_required
def upload():
    try:
        if request.method == 'POST':
            # get name from the form & use secure_fileiname for
            # edgy and unifrom file name formatting
            name = secure_filename(request.form['name'])
            # check if name already exists
            name_taken = Song.query.filter_by(name=name).first()
            # if found redirect back to upload
            if name_taken is not None:
                # alert user
                flash("name taken")
                # redirect
                return redirect(url_for("player_bp.upload"))
            # get files
            webm_file = request.files["webm"]
            mp3_file = request.files["mp3"]
            # get the mp3 & webm file & filenames and sanitize them
            webm_filename = secure_filename(name + ".webm")
            mp3_filename = secure_filename(name + ".mp3")
            # assign url to audio file
            webm_url = audio.url(webm_filename)
            mp3_url = audio.url(mp3_filename)
            # save audio files
            webm_file.save(os.path.join(current_app.config["UPLOADS_DEFAULT_DEST"], webm_filename))
            mp3_file.save(os.path.join(current_app.config["UPLOADS_DEFAULT_DEST"], mp3_filename))
            # create song object
            song = Song(name=name, webm_url=webm_url, webm_filename=webm_filename,
                        mp3_url=mp3_url, mp3_filename=mp3_filename)
            # insert song into database
            db.session.add(song)
            db.session.commit()
            db.session.close()
            # alert user
            flash('uploaded')
            # redirect to cms
            return redirect(url_for('player_bp.cms'))
        return render_template('upload.html')
    except:
        abort(500)

templates/about.html
{% extends "base.html" %} {% block head %} {{ super() }} {% endblock %} {% block
content %}
<div class="text-container">
  <h1><span class="text-underline"> About </span></h1>
  <p>
    a web music player with an easily configurable CMS. Built using
    Flask/HowerJs/SQLite. It has uploading, publishing, and deleting
    capabilities. Authentication is handled using Flask Login.
  </p>
  <p class="link">
    <a href="https://github.com/abmamo/music"><i class="fa fa-github-square fa-2x"></i></a>
  </p>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
  {% block head %}
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" />
  <title>tunez</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  {% endblock %}
</head>

<body>
  <div id="nav" class="overlay">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <div class="overlay-content">
      <a href="{{ url_for('player_bp.home') }}">Home</a>
      <a href="{{ url_for('player_bp.about') }}">About</a>
      {% if not current_user.is_authenticated %}
      <a href="{{ url_for('player_bp.signin') }}">Sign In</a>
      {% endif %}
      {% if current_user.is_authenticated %}
      <a href="{{ url_for('player_bp.cms') }}">CMS</a>
      <a href="{{ url_for('player_bp.upload') }}">Upload</a>
      <a href="{{ url_for('player_bp.signout') }}">Sign Out</a>
      {% endif %}
    </div>
  </div>

  <div id="navbar">
    <span id="menu-icon" onclick="openNav()">&#9776;</span>
  </div>

  <div id="content" class="container">
    <div id="snackbar">
      {% with messages = get_flashed_messages() %} {% if messages %} {% for
        message in messages %} {{ message }} {% endfor %} {% endif %} {% endwith
        %}
    </div>
    {% block content %}{% endblock %}
  </div>

  <script>
    function openNav() {
      document.getElementById("nav").style.width = "100%";
    }

    function closeNav() {
      document.getElementById("nav").style.width = "0%";
    }
  </script>
  {% with messages = get_flashed_messages() %} {% if messages %} {% for
    message in messages %} {% if message is defined and message|length %}
  <script>
    function showAlert() {
      // Get the snackbar DIV
      var x = document.getElementById("snackbar");

      // Add the "show" class to DIV
      x.className = "show";

      // After 3 seconds, remove the show class from DIV
      setTimeout(function () {
        x.className = x.className.replace("show", "");
      }, 3000);
    }
    window.onload = showAlert;
  </script>
  {% endif %} {% endfor %} {% endif %} {% endwith %}
</body>

</html>

templates/change.html
{% extends 'base.html' %} {% block head %} {{ super() }}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/form.css') }}"
/>
{% endblock %} {% block content %}
<div class="text-container">
  <h1><span class="text-underline"> SIGN IN </span></h1>
  <form
    action="{{ url_for('reset_with_token', token=token) }}"
    method="POST"
    enctype="multipart/form-data"
  >
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <input type="password" name="password" placeholder="password" />
    <input type="submit" value="Change Password" />
  </form>
</div>
{% endblock %}

templates/cms.html
{% extends "base.html" %} {% block head %} {{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/form.css') }}" />
{% endblock %} {% block content %}
<div class="container song-container">
  <div class="row">
    {% for song in songs %}
    <div class="col s12m4l4">
      <div class="song-card">
        <div class="container">
          <div class="row">
            <div class="col s12m4l4">
              <form action="{{ url_for('player_bp.delete', id = song.id) }}" method="POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <input type="submit" value="delete" />
              </form>
            </div>
            <div class="col s12m4l4">
              <form action="{{ url_for('player_bp.publish', id = song.id) }}" method="POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <input type="submit" value="publish" />
              </form>
            </div>
            <div class="col s12m4l4">
              <form action="{{ url_for('player_bp.unpublish', id = song.id) }}" method="POST">
                <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
                <input type="submit" value="unpublish" />
              </form>
            </div>
          </div>
          <p>{{ song.name }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

templates/error.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description" content="teret stories page" />
  <meta name="author" content="Abenezer Mamo" />
  <title>error</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css" />
  <link href="http://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="{{ url_for('static', filename='css/gallery-materialize.min.css') }}" />
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
  <script src="https://kit.fontawesome.com/d11a9ce67f.js"></script>
</head>

<body>
  <header>
    <section class="header-content valign-wrapper">
      <div class="container">
        <span class="header-title">
          <h1>{{ status_code }}</h1>
        </span>
        <p class="sub-text">{{ message }}</p>
      </div>
    </section>
  </header>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>

</html>

templates/home.html
{% extends "base.html" %} {% block head %} {{ super() }} {% endblock %} {% block
content %}
<!-- Top Info -->
<div id="title">
  <span id="track"></span>
  <div id="timer">0:00</div>
  <div id="duration">0:00</div>
</div>

<!-- Controls -->
<div class="controlsOuter">
  <div class="controlsInner">
    <div id="loading"></div>
    <div class="btn" id="playBtn"></div>
    <div class="btn" id="pauseBtn"></div>
    <div class="btn" id="prevBtn"></div>
    <div class="btn" id="nextBtn"></div>
  </div>
  <div class="btn" id="playlistBtn"></div>
  <div class="btn" id="volumeBtn"></div>
</div>

<!-- Progress -->
<div id="waveform"></div>
<div id="bar"></div>
<div id="progress"></div>

<!-- Playlist -->
<div id="playlist">
  <div id="list"></div>
</div>

<!-- Volume -->
<div id="volume" class="fadeout">
  <div id="barFull" class="bar"></div>
  <div id="barEmpty" class="bar"></div>
  <div id="sliderBtn"></div>
</div>

<!-- Scripts -->
<script src="{{ url_for('static', filename='js/howler.core.js')}}"></script>
<script src="{{ url_for('static', filename='js/siriwave.js') }}"></script>
<script>
        // Cache references to DOM elements.
  var elms = [
    "track",
    "timer",
    "duration",
    "playBtn",
    "pauseBtn",
    "prevBtn",
    "nextBtn",
    "playlistBtn",
    "volumeBtn",
    "progress",
    "bar",
    "wave",
    "loading",
    "playlist",
    "list",
    "volume",
    "barEmpty",
    "barFull",
    "sliderBtn"
  ];
  elms.forEach(function(elm) {
    window[elm] = document.getElementById(elm);
  });

  /**
   * Player class containing the state of our playlist and where we are in it.
   * Includes all methods for playing, skipping, updating the display, etc.
   * @param {Array} playlist Array of objects with playlist song details ({title, file, howl}).
   */
  var Player = function(playlist) {
    this.playlist = playlist;
    this.index = 0;

    // Display the title of the first track.
    track.innerHTML = "1. " + playlist[0].title;

    // Setup the playlist display.
    playlist.forEach(function(song) {
      var div = document.createElement("div");
      div.className = "list-song";
      div.innerHTML = song.title;
      div.onclick = function() {
        player.skipTo(playlist.indexOf(song));
      };
      list.appendChild(div);
    });
  };
  Player.prototype = {
    /**
     * Play a song in the playlist.
     * @param  {Number} index Index of the song in the playlist (leave empty to play the first or current).
     */
    play: function(index) {
      var self = this;
      var sound;

      index = typeof index === "number" ? index : self.index;
      var data = self.playlist[index];

      // If we already loaded this track, use the current one.
      // Otherwise, setup and load a new Howl.
      if (data.howl) {
        sound = data.howl;
      } else {
        sound = data.howl = new Howl({
          src: [
            "./static/audio/" + data.file + ".webm",
            "./static/audio/" + data.file + ".mp3"
          ],
          html5: true, // Force to HTML5 so that the audio can stream in (best for large files).
          onplay: function() {
            // Display the duration.
            duration.innerHTML = self.formatTime(Math.round(sound.duration()));

            // Start upating the progress of the track.
            requestAnimationFrame(self.step.bind(self));

            // Start the wave animation if we have already loaded
            wave.container.style.display = "block";
            bar.style.display = "none";
            pauseBtn.style.display = "block";
          },
          onload: function() {
            // Start the wave animation.
            wave.container.style.display = "block";
            bar.style.display = "none";
            loading.style.display = "none";
          },
          onend: function() {
            // Stop the wave animation.
            wave.container.style.display = "none";
            bar.style.display = "block";
            self.skip("next");
          },
          onpause: function() {
            // Stop the wave animation.
            wave.container.style.display = "none";
            bar.style.display = "block";
          },
          onstop: function() {
            // Stop the wave animation.
            wave.container.style.display = "none";
            bar.style.display = "block";
          },
          onseek: function() {
            // Start upating the progress of the track.
            requestAnimationFrame(self.step.bind(self));
          }
        });
      }

      // Begin playing the sound.
      sound.play();

      // Update the track display.
      track.innerHTML = index + 1 + ". " + data.title;

      // Show the pause button.
      if (sound.state() === "loaded") {
        playBtn.style.display = "none";
        pauseBtn.style.display = "block";
      } else {
        loading.style.display = "block";
        playBtn.style.display = "none";
        pauseBtn.style.display = "none";
      }

      // Keep track of the index we are currently playing.
      self.index = index;
    },

    /**
     * Pause the currently playing track.
     */
    pause: function() {
      var self = this;

      // Get the Howl we want to manipulate.
      var sound = self.playlist[self.index].howl;

      // Puase the sound.
      sound.pause();

      // Show the play button.
      playBtn.style.display = "block";
      pauseBtn.style.display = "none";
    },

    /**
     * Skip to the next or previous track.
     * @param  {String} direction 'next' or 'prev'.
     */
    skip: function(direction) {
      var self = this;

      // Get the next track based on the direction of the track.
      var index = 0;
      if (direction === "prev") {
        index = self.index - 1;
        if (index < 0) {
          index = self.playlist.length - 1;
        }
      } else {
        index = self.index + 1;
        if (index >= self.playlist.length) {
          index = 0;
        }
      }

      self.skipTo(index);
    },

    /**
     * Skip to a specific track based on its playlist index.
     * @param  {Number} index Index in the playlist.
     */
    skipTo: function(index) {
      var self = this;

      // Stop the current track.
      if (self.playlist[self.index].howl) {
        self.playlist[self.index].howl.stop();
      }

      // Reset progress.
      progress.style.width = "0%";

      // Play the new track.
      self.play(index);
    },

    /**
     * Set the volume and update the volume slider display.
     * @param  {Number} val Volume between 0 and 1.
     */
    volume: function(val) {
      var self = this;

      // Update the global volume (affecting all Howls).
      Howler.volume(val);

      // Update the display on the slider.
      var barWidth = (val * 90) / 100;
      barFull.style.width = barWidth * 100 + "%";
      sliderBtn.style.left =
        window.innerWidth * barWidth + window.innerWidth * 0.05 - 25 + "px";
    },

    /**
     * Seek to a new position in the currently playing track.
     * @param  {Number} per Percentage through the song to skip.
     */
    seek: function(per) {
      var self = this;

      // Get the Howl we want to manipulate.
      var sound = self.playlist[self.index].howl;

      // Convert the percent into a seek position.
      if (sound.playing()) {
        sound.seek(sound.duration() * per);
      }
    },

    /**
     * The step called within requestAnimationFrame to update the playback position.
     */
    step: function() {
      var self = this;

      // Get the Howl we want to manipulate.
      var sound = self.playlist[self.index].howl;

      // Determine our current seek position.
      var seek = sound.seek() || 0;
      timer.innerHTML = self.formatTime(Math.round(seek));
      progress.style.width = ((seek / sound.duration()) * 100 || 0) + "%";

      // If the sound is still playing, continue stepping.
      if (sound.playing()) {
        requestAnimationFrame(self.step.bind(self));
      }
    },

    /**
     * Toggle the playlist display on/off.
     */
    togglePlaylist: function() {
      var self = this;
      var display = playlist.style.display === "block" ? "none" : "block";

      setTimeout(
        function() {
          playlist.style.display = display;
        },
        display === "block" ? 0 : 500
      );
      playlist.className = display === "block" ? "fadein" : "fadeout";
    },

    /**
     * Toggle the volume display on/off.
     */
    toggleVolume: function() {
      var self = this;
      var display = volume.style.display === "block" ? "none" : "block";

      setTimeout(
        function() {
          volume.style.display = display;
        },
        display === "block" ? 0 : 500
      );
      volume.className = display === "block" ? "fadein" : "fadeout";
    },

    /**
     * Format the time from seconds to M:SS.
     * @param  {Number} secs Seconds to format.
     * @return {String}      Formatted time.
     */
    formatTime: function(secs) {
      var minutes = Math.floor(secs / 60) || 0;
      var seconds = secs - minutes * 60 || 0;

      return minutes + ":" + (seconds < 10 ? "0" : "") + seconds;
    }
  };

  // Setup our new audio player class and pass it the playlist.
  var player = new Player([
    {% for song in songs %}
      {
        title: '{{ song.name }}',
        file: '{{ song.name }}',
        howl: null
      },
    {% endfor %}
  ]);

  // Bind our player controls.
  playBtn.addEventListener("click", function() {
    player.play();
  });
  pauseBtn.addEventListener("click", function() {
    player.pause();
  });
  prevBtn.addEventListener("click", function() {
    player.skip("prev");
  });
  nextBtn.addEventListener("click", function() {
    player.skip("next");
  });
  waveform.addEventListener("click", function(event) {
    player.seek(event.clientX / window.innerWidth);
  });
  playlistBtn.addEventListener("click", function() {
    player.togglePlaylist();
  });
  playlist.addEventListener("click", function() {
    player.togglePlaylist();
  });
  volumeBtn.addEventListener("click", function() {
    player.toggleVolume();
  });
  volume.addEventListener("click", function() {
    player.toggleVolume();
  });

  // Setup the event listeners to enable dragging of volume slider.
  barEmpty.addEventListener("click", function(event) {
    var per = event.layerX / parseFloat(barEmpty.scrollWidth);
    player.volume(per);
  });
  sliderBtn.addEventListener("mousedown", function() {
    window.sliderDown = true;
  });
  sliderBtn.addEventListener("touchstart", function() {
    window.sliderDown = true;
  });
  volume.addEventListener("mouseup", function() {
    window.sliderDown = false;
  });
  volume.addEventListener("touchend", function() {
    window.sliderDown = false;
  });

  var move = function(event) {
    if (window.sliderDown) {
      var x = event.clientX || event.touches[0].clientX;
      var startX = window.innerWidth * 0.05;
      var layerX = x - startX;
      var per = Math.min(
        1,
        Math.max(0, layerX / parseFloat(barEmpty.scrollWidth))
      );
      player.volume(per);
    }
  };

  volume.addEventListener("mousemove", move);
  volume.addEventListener("touchmove", move);

  // Setup the "waveform" animation.
  var wave = new SiriWave({
    container: waveform,
    width: window.innerWidth,
    height: window.innerHeight * 0.3,
    cover: true,
    speed: 0.03,
    amplitude: 0.7,
    frequency: 2
  });
  wave.start();

  // Update the height of the wave animation.
  // These are basically some hacks to get SiriWave.js to do what we want.
  var resize = function() {
    var height = window.innerHeight * 0.3;
    var width = window.innerWidth;
    wave.height = height;
    wave.height_2 = height / 2;
    wave.MAX = wave.height_2 - 4;
    wave.width = width;
    wave.width_2 = width / 2;
    wave.width_4 = width / 4;
    wave.canvas.height = height;
    wave.canvas.width = width;
    wave.container.style.margin = -(height / 2) + "px auto";

    // Update the position of the slider.
    var sound = player.playlist[player.index].howl;
    if (sound) {
      var vol = sound.volume();
      var barWidth = vol * 0.9;
      sliderBtn.style.left =
        window.innerWidth * barWidth + window.innerWidth * 0.05 - 25 + "px";
    }
  };
  window.addEventListener("resize", resize);
  resize();
</script>
{% endblock %}

templates/request_reset.html
{% extends 'base.html' %} {% block head %} {{ super() }}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/form.css') }}"
/>
{% endblock %} {% block content %}
<div class="text-container">
  <h1><span class="text-underline"> RESET PASSWORD </span></h1>
  <form
    action="{{ url_for('request_reset') }}"
    method="POST"
    enctype="multipart/form-data"
  >
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <input type="text" name="email" placeholder="email" />
    <input type="submit" value="Reset" />
  </form>
</div>
{% endblock %}

templates/reset.html
{% extends 'base.html' %} {% block head %} {{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/form.css') }}" />
{% endblock %} {% block content %}
<div class="text-container">
  <h1><span class="text-underline"> RESET PASSWORD </span></h1>
  <form action="{{ url_for('player_bp.reset') }}" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <div class="row">
      <input type="text" name="email" placeholder="email" />
    </div>
    <div class="row">
      <input type="submit" value="reset" />
    </div>
    <div class="row center-align">
      <a href="{{ url_for('player_bp.home') }}" class="center-align link">
        <span><i class="material-icons">home</i> HOME </span></a>
    </div>
  </form>
</div>
{% endblock %}

templates/reset_with_token.html
{% extends 'base.html' %} {% block head %} {{ super() }}
<link
  rel="stylesheet"
  href="{{ url_for('static', filename='css/form.css') }}"
/>
{% endblock %} {% block content %}
<div class="text-container">
  <h1><span class="text-underline"> SIGN IN </span></h1>
  <form
    action="{{ url_for('reset_with_token', token=token) }}"
    method="POST"
    enctype="multipart/form-data"
  >
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <input type="password" name="password" placeholder="password" />
    <input type="submit" value="Change Password" />
  </form>
</div>
{% endblock %}

templates/signin.html
{% extends 'base.html' %} {% block head %} {{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/form.css') }}" />
{% endblock %} {% block content %}
<div class="text-container">
  <h1><span class="text-underline"> SIGN IN </span></h1>
  <form action="{{ url_for('player_bp.signin') }}" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <div class="row">
      <input type="text" name="email" placeholder="email" />
    </div>
    <div class="row">
      <input type="password" name="password" placeholder="password" />
    </div>
    <div class="row">
      <input type="submit" value="log in" />
    </div>
    <div class="row center-align">
      <a href="{{ url_for('player_bp.reset') }}" class="center-align link">
        <span><i class="material-icons">add_box</i> FORGOT
          PASSWORD</span></a>
    </div>
    <div class="row center-align">
      <a href="{{ url_for('player_bp.home') }}" class="center-align link">
        <span><i class="material-icons">home</i> HOME </span></a>
    </div>
  </form>
</div>
{% endblock %}

templates/upload.html
{% extends 'base.html' %} {% block head %} {{ super() }}
<link rel="stylesheet" href="{{ url_for('static', filename='css/form.css') }}" />
{% endblock %} {% block content %}
<div class="text-container">
  <h1><span class="text-underline"> UPLOAD </span></h1>
  <form action="{{ url_for('player_bp.upload') }}" method="POST" enctype="multipart/form-data">
    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}" />
    <div class="row">
      <input type="text" name="name" placeholder="name" />
    </div>
    <div class="row">
      <p class="form-label">mp3: </p><input type="file" name="mp3" placeholder="mp3" />
    </div>
    <div class="row">
      <p class="form-label">webm: </p><input type="file" name="webm" placeholder="webm" />
    </div>
    <div class="row">
      <input type="submit" value="upload" />
    </div>
  </form>
</div>
{% endblock %}